service: todo-app

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: todos
          method: get
      - http:
          path: todos
          method: post
      - http:
          path: todos/{id}
          method: delete
